# This environment includes all the required packages for this repo including running the test suite.
name: leafwaxtools
channels:
  - default
  - conda-forge
dependencies:
  - python=3.12.*
  - pip
  - pytest
  - pytest-cov
  - numpy
  - pandas
  - openpyxl
  - scikit-learn
  - scipy
  - scikit-bio
  - pip:
    - '-e .'
